### PR TITLE
refactor(src): migrate `loglevelnext` into `webpack-log`

### LINKED ISSUE #6: Replace `loglevelnext`

### PR DESCRIPTION
**Pull request by michael-ciniawsky**
Migrates [`loglevelnext`](https://github.com/shellscape/loglevelnext) into `webpack-log` and removes the original dependency

### Type

- [x] Refactor

### Issues

- Fixes #6 

### SemVer

- [x] Patch

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
Looks we need add tests

**Comment by michael-ciniawsky** [comment]
Yes :)

**Review by alexander-akait — APPROVED** [review]

**Comment by alexander-akait** [comment]
@michael-ciniawsky i think we should release new version

**Comment by michael-ciniawsky** [comment]
Double checking if I missed anything obvious right now :). #9 ? Can we can find consensus on the README formatting ?

**Comment by alexander-akait** [comment]
@michael-ciniawsky Leave it as is now, we have a lot of other problems and issues with more priority than README formatting

**Pull request merged**
